# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    service_mysql:
        class: AppBundle\Service\Mysql
        arguments: [ "@doctrine.orm.entity_manager" ]
    service_redis:
        class: AppBundle\Service\Redis
        arguments: ["@snc_redis.default"]
